### ISSUE TITLE
Whisper Transcription not working

### ISSUE THREAD

**Issue by Vander1nde21** [Mozer/talk-llama-fast#5]
So I've done all the steps. but when I ran talk-llama-wav2lip.bat it said that cudart64_110.dll, cublasLt64_11.dll and cublas64_11.dll was missing. so I went online, downloaded those DLLs and dropped them in the main directory and it worked. No errors after that.  I then tweaked the parameters to my liking alongside the audio input device. However, I'm speaking and nothing is transcribing.  I feel like this may be an issue with Whisper.

**Comment by Mozer** [comment]
1. check if the mic is working in some other program, e.g. Audacity. And it should be set as default in windows. If there are no visible errors, I guess it's the problem with the mic, try another mic. 

2. One more guess - if there non latin symbols in the mic name, it can cause problems. Try to copy command from talk-llama-wav2lip.bat, and paste into cmd opened in directory where the bats are. Run. It can solve problems with non-latin symbols.

**Comment by Vander1nde21** [comment]
I used audacity and other software and the mic is working fine. my mic is simply named (USB AUDIO DEVICE) and has no non latin symbols. also yeah I installed CUDA toolkit setup installer from NVIDIA just to see if anything happens, but the dll errors still persisted. But when i downloaded each the cudart64_110.dll, cublasLt64_11.dll and cublas64_11.dll files from .dll-files.com it got rid of the errors  

![Screenshot 2024-04-07 201751](https://github.com/Mozer/talk-llama-fast/assets/78788365/aae6bf4d-868f-4e80-b909-dee21d7a70cb)

**Comment by Mozer** [comment]
Try to enable "Listen to this device" in mic settings. It might help or can find a problem. After that - restart talk-llama
![Image2](https://github.com/Mozer/talk-llama-fast/assets/1599013/945affc1-72a8-4d6e-809f-994c24b49d4c)

**Comment by Vander1nde21** [comment]
Just enabled it. I can hear my own voice but nothing is transcribing still. 
![Screenshot 2024-04-07 211433](https://github.com/Mozer/talk-llama-fast/assets/78788365/8a862076-2539-4021-8b79-fcec99318425)

**Comment by Mozer** [comment]
Try to run from cmd instead of .bat. Copy and paste command. cmd should be run from the same dir. It helped one guy with airpods mic not working.

**Comment by Vander1nde21** [comment]
Yeah just tried that. Ran CMD from the directory where all the bat files are alongside listen to this device being enabled at the same time and still no luck.

**Comment by Mozer** [comment]
What version of windows are you using? Can you you try with some other mic? If you don't have one you can use "wo mic" android app to pass mic sound from your phone to Windows.

**Comment by Mozer** [comment]
Try to restart everything. This error is non critical, it just says that xtts won't generate audio, because it detected noise (your speech). But if there's no noise - and xtts still says there is - it's a problem. What version of In talk-llama-fast are you using?

 In talk-llama-fast-v0.1.3 exe i updated the location of xtts control file xtts_play_allowed.txt (now its in temp dir). Maybe you are using a new exe and old xtts. Old xtts can't find new xtts_play_allowed.txt. simple solution use old 0.1.2 exe with my old xtts.

**Comment by Vander1nde21** [comment]
Ok, updated miniconda and completely done a clean install and it's working better than it did before, and that xtts error is gone now. however it's wav2lip that has an error this time.

this is what it says in the silly_extras.bat wav2lip server for each time a text is generated:

in wav2lip_server_generate: is busy: 0, face_detect_running: 0, chunk: 42, chunk_needed: 42, reply: 3
Error: tts_out/out_42.wav file is not found

NOTE: once the silly_extras.bat file starts, i get a few errors that mention ffmpeg. maybe this could be the problem.

![image](https://github.com/Mozer/talk-llama-fast/assets/78788365/43ed2de3-197d-47de-b4af-de3018662c78)

**Comment by Mozer** [comment]
Error: tts_out/out_42.wav file is not found - means that /tts_out/ dir is wrong in xtts_wav2lip.bat. But as i see in your screenshot it can find your tts wavs. 

Did you copy openh264-1.8.0-win64.dll to /system32 or /ffmpeg/bin dir? If didn't - copy it, if you did - delete it (or rename), maybe it's causing error with videowriter.

**Comment by Vander1nde21** [comment]
ah yes those first two ffmpeg and openh264 errors have dissapeared now, but in the talk-llama-wav2lip.bat I set --vad-start-thold 0 and i still get this error:

in wav2lip_server_generate: is busy: 0, face_detect_running: 0, chunk: 1, chunk_needed: 1, reply: 0
Error: tts_out/out_1.wav file is not found
127.0.0.1 - - [09/Apr/2024 08:55:17] "GET /api/wav2lip/generate/Default/cuda/out_1/latest/1/0 HTTP/1.1" 200 -
1712616918.2462685 in wav2lip gen server chunk:2_1

**Comment by Vander1nde21** [comment]
Nevermind it's all fixed now. Thanks so much @Mozer
